//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountStudentFeesList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountStudentFeesList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.AccountStudentFeesList", typeof(AccountStudentFeesList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Select Academic Year.
        /// </summary>
        public static string AcademicYearIDerror {
            get {
                return ResourceManager.GetString("AcademicYearIDerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcademicYear.
        /// </summary>
        public static string AcademicYearName {
            get {
                return ResourceManager.GetString("AcademicYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books Fees.
        /// </summary>
        public static string BooksFees {
            get {
                return ResourceManager.GetString("BooksFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Books Fees.
        /// </summary>
        public static string BooksFeeserror {
            get {
                return ResourceManager.GetString("BooksFeeserror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Fees.
        /// </summary>
        public static string StudyFees {
            get {
                return ResourceManager.GetString("StudyFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Study Fees.
        /// </summary>
        public static string StudyFeeserror {
            get {
                return ResourceManager.GetString("StudyFeeserror", resourceCulture);
            }
        }
    }
}
