//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountCustomer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountCustomer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.AccountCustomer", typeof(AccountCustomer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountTree.
        /// </summary>
        public static string AccountTree {
            get {
                return ResourceManager.GetString("AccountTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Tree.
        /// </summary>
        public static string AccountTreeID {
            get {
                return ResourceManager.GetString("AccountTreeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Account Tree.
        /// </summary>
        public static string AccountTreeIDError {
            get {
                return ResourceManager.GetString("AccountTreeIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Number.
        /// </summary>
        public static string BankAccountNumber {
            get {
                return ResourceManager.GetString("BankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Branch.
        /// </summary>
        public static string BankBranchID {
            get {
                return ResourceManager.GetString("BankBranchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityID {
            get {
                return ResourceManager.GetString("CityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Register.
        /// </summary>
        public static string Commercialregister {
            get {
                return ResourceManager.GetString("Commercialregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer envoy.
        /// </summary>
        public static string Customer_Employee {
            get {
                return ResourceManager.GetString("Customer_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Activity.
        /// </summary>
        public static string Customeractivity {
            get {
                return ResourceManager.GetString("Customeractivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ArabicName.
        /// </summary>
        public static string CustomerNameAr {
            get {
                return ResourceManager.GetString("CustomerNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Customer Arabic Name.
        /// </summary>
        public static string CustomerNameArError {
            get {
                return ResourceManager.GetString("CustomerNameArError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Customer Name.
        /// </summary>
        public static string CustomerNameError {
            get {
                return ResourceManager.GetString("CustomerNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Number.
        /// </summary>
        public static string CustomerNumber {
            get {
                return ResourceManager.GetString("CustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string Depeit {
            get {
                return ResourceManager.GetString("Depeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Employee.
        /// </summary>
        public static string Emp_ID {
            get {
                return ResourceManager.GetString("Emp_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Balance.
        /// </summary>
        public static string FBalance {
            get {
                return ResourceManager.GetString("FBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN1.
        /// </summary>
        public static string IBAN1 {
            get {
                return ResourceManager.GetString("IBAN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN2.
        /// </summary>
        public static string IBAN2 {
            get {
                return ResourceManager.GetString("IBAN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN3.
        /// </summary>
        public static string IBAN3 {
            get {
                return ResourceManager.GetString("IBAN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        public static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Stop.
        /// </summary>
        public static string ReasonStop {
            get {
                return ResourceManager.GetString("ReasonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type activity.
        /// </summary>
        public static string Typeofactivity {
            get {
                return ResourceManager.GetString("Typeofactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
