//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountTrees {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountTrees() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.AccountTrees", typeof(AccountTrees).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        public static string AccountCode {
            get {
                return ResourceManager.GetString("AccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        public static string AccountID {
            get {
                return ResourceManager.GetString("AccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Level.
        /// </summary>
        public static string AccountLevel {
            get {
                return ResourceManager.GetString("AccountLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Account Level.
        /// </summary>
        public static string AccountLevelError {
            get {
                return ResourceManager.GetString("AccountLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name Ar.
        /// </summary>
        public static string AccountNameAr {
            get {
                return ResourceManager.GetString("AccountNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Account  Name.
        /// </summary>
        public static string AccountNameArError {
            get {
                return ResourceManager.GetString("AccountNameArError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Existed.
        /// </summary>
        public static string AccountNameArExist {
            get {
                return ResourceManager.GetString("AccountNameArExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name EN.
        /// </summary>
        public static string AccountNameEN {
            get {
                return ResourceManager.GetString("AccountNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Account  Name.
        /// </summary>
        public static string AccountNameENError {
            get {
                return ResourceManager.GetString("AccountNameENError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Existed.
        /// </summary>
        public static string AccountNameEnExist {
            get {
                return ResourceManager.GetString("AccountNameEnExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountParent {
            get {
                return ResourceManager.GetString("AccountParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Account  Type.
        /// </summary>
        public static string AccountParentError {
            get {
                return ResourceManager.GetString("AccountParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Parent Name Ar.
        /// </summary>
        public static string AccountParentNameAr {
            get {
                return ResourceManager.GetString("AccountParentNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub Account.
        /// </summary>
        public static string Addsubaccount {
            get {
                return ResourceManager.GetString("Addsubaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string BankCurrencyID {
            get {
                return ResourceManager.GetString("BankCurrencyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Currency.
        /// </summary>
        public static string BankCurrencyIDError {
            get {
                return ResourceManager.GetString("BankCurrencyIDError", resourceCulture);
            }
        }
    }
}
