//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccStudentFees {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccStudentFees() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.AccStudentFees", typeof(AccStudentFees).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Amount.
        /// </summary>
        public static string Amounterror {
            get {
                return ResourceManager.GetString("Amounterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Statement.
        /// </summary>
        public static string bankStatement {
            get {
                return ResourceManager.GetString("bankStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Paid.
        /// </summary>
        public static string IsPaid {
            get {
                return ResourceManager.GetString("IsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Date.
        /// </summary>
        public static string OperationDate {
            get {
                return ResourceManager.GetString("OperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Operation Date.
        /// </summary>
        public static string OperationDateerror {
            get {
                return ResourceManager.GetString("OperationDateerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total Paid Amount.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Payment Type.
        /// </summary>
        public static string PaymentTypeerror {
            get {
                return ResourceManager.GetString("PaymentTypeerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Way.
        /// </summary>
        public static string PaymentWay {
            get {
                return ResourceManager.GetString("PaymentWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Payment Way.
        /// </summary>
        public static string PaymentWayerror {
            get {
                return ResourceManager.GetString("PaymentWayerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total RemainderAmount.
        /// </summary>
        public static string remainderAmount {
            get {
                return ResourceManager.GetString("remainderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Acdemic ID.
        /// </summary>
        public static string StudAcdID {
            get {
                return ResourceManager.GetString("StudAcdID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Configration ID.
        /// </summary>
        public static string StudentConfigrationID {
            get {
                return ResourceManager.GetString("StudentConfigrationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total After Tax.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total BeforeTax.
        /// </summary>
        public static string totalBeforeTax {
            get {
                return ResourceManager.GetString("totalBeforeTax", resourceCulture);
            }
        }
    }
}
