//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccStudentConfigrations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccStudentConfigrations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.AccStudentConfigrations", typeof(AccStudentConfigrations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acadimic Year.
        /// </summary>
        public static string AcademicYear {
            get {
                return ResourceManager.GetString("AcademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books Discount.
        /// </summary>
        public static string BooksDiscount {
            get {
                return ResourceManager.GetString("BooksDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books Net Price.
        /// </summary>
        public static string BooksNetPrice {
            get {
                return ResourceManager.GetString("BooksNetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books Price.
        /// </summary>
        public static string BooksPrice {
            get {
                return ResourceManager.GetString("BooksPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Discount.
        /// </summary>
        public static string BusDiscount {
            get {
                return ResourceManager.GetString("BusDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Fees.
        /// </summary>
        public static string BusFees {
            get {
                return ResourceManager.GetString("BusFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus .
        /// </summary>
        public static string BusID {
            get {
                return ResourceManager.GetString("BusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Net Price.
        /// </summary>
        public static string BusNetPrice {
            get {
                return ResourceManager.GetString("BusNetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS Books Discount.
        /// </summary>
        public static string IsBooksDiscount {
            get {
                return ResourceManager.GetString("IsBooksDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS bus Discount.
        /// </summary>
        public static string ISbusDiscount {
            get {
                return ResourceManager.GetString("ISbusDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS Study Discount.
        /// </summary>
        public static string isStudyDiscount {
            get {
                return ResourceManager.GetString("isStudyDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS Uniform Discount.
        /// </summary>
        public static string isUniformDiscount {
            get {
                return ResourceManager.GetString("isUniformDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Date.
        /// </summary>
        public static string OperationDate {
            get {
                return ResourceManager.GetString("OperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Select Date.
        /// </summary>
        public static string OperationDateerror {
            get {
                return ResourceManager.GetString("OperationDateerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Acadimic ID.
        /// </summary>
        public static string StudentAcdID {
            get {
                return ResourceManager.GetString("StudentAcdID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Fees.
        /// </summary>
        public static string StudyFees {
            get {
                return ResourceManager.GetString("StudyFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Fees Discount.
        /// </summary>
        public static string StudyFeesDiscount {
            get {
                return ResourceManager.GetString("StudyFeesDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Net Fees.
        /// </summary>
        public static string StudyNetFees {
            get {
                return ResourceManager.GetString("StudyNetFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        public static string TaxRate {
            get {
                return ResourceManager.GetString("TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Tax Rate.
        /// </summary>
        public static string TaxRateerror {
            get {
                return ResourceManager.GetString("TaxRateerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Type.
        /// </summary>
        public static string TripType {
            get {
                return ResourceManager.GetString("TripType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Discount.
        /// </summary>
        public static string UniformDiscount {
            get {
                return ResourceManager.GetString("UniformDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Net Price.
        /// </summary>
        public static string UniformNetPrice {
            get {
                return ResourceManager.GetString("UniformNetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Price.
        /// </summary>
        public static string UniformPrice {
            get {
                return ResourceManager.GetString("UniformPrice", resourceCulture);
            }
        }
    }
}
