//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssetTrees {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetTrees() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.AssetTrees", typeof(AssetTrees).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub Asset.
        /// </summary>
        public static string AddsubAsset {
            get {
                return ResourceManager.GetString("AddsubAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Code.
        /// </summary>
        public static string AssetCode {
            get {
                return ResourceManager.GetString("AssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset ID.
        /// </summary>
        public static string AssetID {
            get {
                return ResourceManager.GetString("AssetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Level.
        /// </summary>
        public static string AssetLevel {
            get {
                return ResourceManager.GetString("AssetLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Asset Level.
        /// </summary>
        public static string AssetLevelError {
            get {
                return ResourceManager.GetString("AssetLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Name Ar.
        /// </summary>
        public static string AssetNameAr {
            get {
                return ResourceManager.GetString("AssetNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Asset  Name.
        /// </summary>
        public static string AssetNameArError {
            get {
                return ResourceManager.GetString("AssetNameArError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Existed.
        /// </summary>
        public static string AssetNameArExist {
            get {
                return ResourceManager.GetString("AssetNameArExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Name EN.
        /// </summary>
        public static string AssetNameEN {
            get {
                return ResourceManager.GetString("AssetNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Asset  Name.
        /// </summary>
        public static string AssetNameENError {
            get {
                return ResourceManager.GetString("AssetNameENError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Parent.
        /// </summary>
        public static string AssetParent {
            get {
                return ResourceManager.GetString("AssetParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Asset  Parent.
        /// </summary>
        public static string AssetParentError {
            get {
                return ResourceManager.GetString("AssetParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Parent Name Ar.
        /// </summary>
        public static string AssetParentNameAr {
            get {
                return ResourceManager.GetString("AssetParentNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string BankCurrencyID {
            get {
                return ResourceManager.GetString("BankCurrencyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Currency.
        /// </summary>
        public static string BankCurrencyIDError {
            get {
                return ResourceManager.GetString("BankCurrencyIDError", resourceCulture);
            }
        }
    }
}
