//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Bank_Branch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bank_Branch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.Bank_Branch", typeof(Bank_Branch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Branch Name.
        /// </summary>
        public static string ArabicBranchName {
            get {
                return ResourceManager.GetString("ArabicBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Arabic Branch Name.
        /// </summary>
        public static string ArabicBranchNameError {
            get {
                return ResourceManager.GetString("ArabicBranchNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank ID.
        /// </summary>
        public static string BankID {
            get {
                return ResourceManager.GetString("BankID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Bank.
        /// </summary>
        public static string BankIDError {
            get {
                return ResourceManager.GetString("BankIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankName.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Address.
        /// </summary>
        public static string BranchAddress {
            get {
                return ResourceManager.GetString("BranchAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Branch Address.
        /// </summary>
        public static string BranchAddressError {
            get {
                return ResourceManager.GetString("BranchAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Fax.
        /// </summary>
        public static string BranchFax {
            get {
                return ResourceManager.GetString("BranchFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Branch Fax.
        /// </summary>
        public static string BranchFaxError {
            get {
                return ResourceManager.GetString("BranchFaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Mobile.
        /// </summary>
        public static string BranchMobile {
            get {
                return ResourceManager.GetString("BranchMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Branch Mobile.
        /// </summary>
        public static string BranchMobileError {
            get {
                return ResourceManager.GetString("BranchMobileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Phone.
        /// </summary>
        public static string BranchPhone {
            get {
                return ResourceManager.GetString("BranchPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Branch phone.
        /// </summary>
        public static string BranchPhoneError {
            get {
                return ResourceManager.GetString("BranchPhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Branch Name.
        /// </summary>
        public static string EnglishBranchName {
            get {
                return ResourceManager.GetString("EnglishBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter English Branch Name.
        /// </summary>
        public static string EnglishBranchNameError {
            get {
                return ResourceManager.GetString("EnglishBranchNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
    }
}
