//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Bank {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bank() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.Bank", typeof(Bank).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter AccountNumber.
        /// </summary>
        public static string AccountNumberError {
            get {
                return ResourceManager.GetString("AccountNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Name  (Arabic).
        /// </summary>
        public static string ArabicBankAccName {
            get {
                return ResourceManager.GetString("ArabicBankAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name (Arabic).
        /// </summary>
        public static string ArabicBankName {
            get {
                return ResourceManager.GetString("ArabicBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Bank Account Name (Arabic).
        /// </summary>
        public static string bankAccArError {
            get {
                return ResourceManager.GetString("bankAccArError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Name.
        /// </summary>
        public static string BankAccEnglishName {
            get {
                return ResourceManager.GetString("BankAccEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Bank Account Name .
        /// </summary>
        public static string bankAccError {
            get {
                return ResourceManager.GetString("bankAccError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Arabic Bank Name.
        /// </summary>
        public static string bankArError {
            get {
                return ResourceManager.GetString("bankArError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        public static string BankBranchName {
            get {
                return ResourceManager.GetString("BankBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Branch Name.
        /// </summary>
        public static string BankBranchNameError {
            get {
                return ResourceManager.GetString("BankBranchNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankEnglishName {
            get {
                return ResourceManager.GetString("BankEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter  Bank Name.
        /// </summary>
        public static string bankError {
            get {
                return ResourceManager.GetString("bankError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank ID.
        /// </summary>
        public static string BankID {
            get {
                return ResourceManager.GetString("BankID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Description.
        /// </summary>
        public static string DescriptionError {
            get {
                return ResourceManager.GetString("DescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance.
        /// </summary>
        public static string OpeningBalance {
            get {
                return ResourceManager.GetString("OpeningBalance", resourceCulture);
            }
        }
    }
}
