//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusCost {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusCost() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.BusCost", typeof(BusCost).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus .
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusDoubleTrip.
        /// </summary>
        public static string BusDoubleTrip {
            get {
                return ResourceManager.GetString("BusDoubleTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Bus Double Trip Cost.
        /// </summary>
        public static string BusDoubleTripError {
            get {
                return ResourceManager.GetString("BusDoubleTripError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Bus Number.
        /// </summary>
        public static string BusError {
            get {
                return ResourceManager.GetString("BusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Number.
        /// </summary>
        public static string BusNumber {
            get {
                return ResourceManager.GetString("BusNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Bus Number .
        /// </summary>
        public static string BusNumberError {
            get {
                return ResourceManager.GetString("BusNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Single Trip Cost.
        /// </summary>
        public static string BusSingleTrip {
            get {
                return ResourceManager.GetString("BusSingleTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Bus Single Trip Cost.
        /// </summary>
        public static string BusSingleTripError {
            get {
                return ResourceManager.GetString("BusSingleTripError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Station.
        /// </summary>
        public static string BusStation {
            get {
                return ResourceManager.GetString("BusStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Bus Stations.
        /// </summary>
        public static string BusStationError {
            get {
                return ResourceManager.GetString("BusStationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
    }
}
