//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.Buses", typeof(Buses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus ID.
        /// </summary>
        public static string BusID {
            get {
                return ResourceManager.GetString("BusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus No.
        /// </summary>
        public static string BusNo {
            get {
                return ResourceManager.GetString("BusNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter BusNo.
        /// </summary>
        public static string BusNoError {
            get {
                return ResourceManager.GetString("BusNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Type.
        /// </summary>
        public static string BusType {
            get {
                return ResourceManager.GetString("BusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Bus Type.
        /// </summary>
        public static string BusTypeError {
            get {
                return ResourceManager.GetString("BusTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChassisNo.
        /// </summary>
        public static string ChassisNo {
            get {
                return ResourceManager.GetString("ChassisNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Chassis No.
        /// </summary>
        public static string ChassisNoError {
            get {
                return ResourceManager.GetString("ChassisNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssuedFrom.
        /// </summary>
        public static string IssuedFrom {
            get {
                return ResourceManager.GetString("IssuedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Issued From.
        /// </summary>
        public static string IssuedFromError {
            get {
                return ResourceManager.GetString("IssuedFromError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicenseEnd.
        /// </summary>
        public static string LicenseEnd {
            get {
                return ResourceManager.GetString("LicenseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter License End.
        /// </summary>
        public static string LicenseEndError {
            get {
                return ResourceManager.GetString("LicenseEndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License No.
        /// </summary>
        public static string LicenseNo {
            get {
                return ResourceManager.GetString("LicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter LicenseNo.
        /// </summary>
        public static string LicenseNoError {
            get {
                return ResourceManager.GetString("LicenseNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Start.
        /// </summary>
        public static string LicenseStart {
            get {
                return ResourceManager.GetString("LicenseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter License Start.
        /// </summary>
        public static string LicenseStartError {
            get {
                return ResourceManager.GetString("LicenseStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactur .
        /// </summary>
        public static string Manufactur {
            get {
                return ResourceManager.GetString("Manufactur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Manufactur.
        /// </summary>
        public static string ManufacturError {
            get {
                return ResourceManager.GetString("ManufacturError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Model.
        /// </summary>
        public static string ModelError {
            get {
                return ResourceManager.GetString("ModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers Number.
        /// </summary>
        public static string PassengersNumber {
            get {
                return ResourceManager.GetString("PassengersNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Passengers Number.
        /// </summary>
        public static string PassengersNumberError {
            get {
                return ResourceManager.GetString("PassengersNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Year.
        /// </summary>
        public static string YearError {
            get {
                return ResourceManager.GetString("YearError", resourceCulture);
            }
        }
    }
}
