//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class chequesPayable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal chequesPayable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.chequesPayable", typeof(chequesPayable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select Acount.
        /// </summary>
        public static string AccountError {
            get {
                return ResourceManager.GetString("AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        public static string AccountTreeCode {
            get {
                return ResourceManager.GetString("AccountTreeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Account.
        /// </summary>
        public static string AccountTreeID {
            get {
                return ResourceManager.GetString("AccountTreeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please selectaccount.
        /// </summary>
        public static string AccountTreeIDError {
            get {
                return ResourceManager.GetString("AccountTreeIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountName {
            get {
                return ResourceManager.GetString("AmountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter Amount.
        /// </summary>
        public static string AmountNameError {
            get {
                return ResourceManager.GetString("AmountNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Branch.
        /// </summary>
        public static string Bank_Branch {
            get {
                return ResourceManager.GetString("Bank_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bank Branch.
        /// </summary>
        public static string Bank_BranchError {
            get {
                return ResourceManager.GetString("Bank_BranchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bank Currency Type.
        /// </summary>
        public static string BankCurrencyIDError {
            get {
                return ResourceManager.GetString("BankCurrencyIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Date.
        /// </summary>
        public static string Cheque_Date {
            get {
                return ResourceManager.GetString("Cheque_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Number.
        /// </summary>
        public static string chequeNumber {
            get {
                return ResourceManager.GetString("chequeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection Date.
        /// </summary>
        public static string collection_Date {
            get {
                return ResourceManager.GetString("collection_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Collection  Date.
        /// </summary>
        public static string collection_DateError {
            get {
                return ResourceManager.GetString("collection_DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection Date.
        /// </summary>
        public static string collectionDate {
            get {
                return ResourceManager.GetString("collectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select Collection Date.
        /// </summary>
        public static string collectionDateError {
            get {
                return ResourceManager.GetString("collectionDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost center.
        /// </summary>
        public static string costcenter {
            get {
                return ResourceManager.GetString("costcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cost Center.
        /// </summary>
        public static string costcenterError {
            get {
                return ResourceManager.GetString("costcenterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Credit Account.
        /// </summary>
        public static string CreditError {
            get {
                return ResourceManager.GetString("CreditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Type.
        /// </summary>
        public static string CurrencyType {
            get {
                return ResourceManager.GetString("CurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Issuance.
        /// </summary>
        public static string DateOfIssuance {
            get {
                return ResourceManager.GetString("DateOfIssuance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string Deliverydate {
            get {
                return ResourceManager.GetString("Deliverydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depit.
        /// </summary>
        public static string Depit {
            get {
                return ResourceManager.GetString("Depit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Depit Error.
        /// </summary>
        public static string DepitError {
            get {
                return ResourceManager.GetString("DepitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please Enter Notes.
        /// </summary>
        public static string DescriptionError {
            get {
                return ResourceManager.GetString("DescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docement Number.
        /// </summary>
        public static string docement_Number {
            get {
                return ResourceManager.GetString("docement_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Docement Number.
        /// </summary>
        public static string docement_NumberError {
            get {
                return ResourceManager.GetString("docement_NumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept  Numbers Only.
        /// </summary>
        public static string docementNumber_num {
            get {
                return ResourceManager.GetString("docementNumber_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Name.
        /// </summary>
        public static string Emp_Name {
            get {
                return ResourceManager.GetString("Emp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string Emp_Name1 {
            get {
                return ResourceManager.GetString("Emp_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        public static string fromAccount {
            get {
                return ResourceManager.GetString("fromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string invoiceDate {
            get {
                return ResourceManager.GetString("invoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Invoice Date.
        /// </summary>
        public static string invoiceDateError {
            get {
                return ResourceManager.GetString("invoiceDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Collected.
        /// </summary>
        public static string isCollected {
            get {
                return ResourceManager.GetString("isCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string ispost {
            get {
                return ResourceManager.GetString("ispost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation Date.
        /// </summary>
        public static string operationDate {
            get {
                return ResourceManager.GetString("operationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select operation Date.
        /// </summary>
        public static string operationDateError {
            get {
                return ResourceManager.GetString("operationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Name.
        /// </summary>
        public static string RecipientName {
            get {
                return ResourceManager.GetString("RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Telephone.
        /// </summary>
        public static string RecipientTel {
            get {
                return ResourceManager.GetString("RecipientTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        public static string toAccount {
            get {
                return ResourceManager.GetString("toAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasury.
        /// </summary>
        public static string Treasury {
            get {
                return ResourceManager.GetString("Treasury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Treasury.
        /// </summary>
        public static string TreasuryError {
            get {
                return ResourceManager.GetString("TreasuryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Treasury.
        /// </summary>
        public static string TreasuryIDCredit {
            get {
                return ResourceManager.GetString("TreasuryIDCredit", resourceCulture);
            }
        }
    }
}
