//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DailyJornal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DailyJornal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.DailyJornal", typeof(DailyJornal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Account.
        /// </summary>
        public static string AccountError {
            get {
                return ResourceManager.GetString("AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Details.
        /// </summary>
        public static string adddetails {
            get {
                return ResourceManager.GetString("adddetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Currency.
        /// </summary>
        public static string BankCurrency {
            get {
                return ResourceManager.GetString("BankCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select currency type.
        /// </summary>
        public static string BankCurrencyIDError {
            get {
                return ResourceManager.GetString("BankCurrencyIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency_Type {
            get {
                return ResourceManager.GetString("Currency_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal details.
        /// </summary>
        public static string Dailydetails {
            get {
                return ResourceManager.GetString("Dailydetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Date.
        /// </summary>
        public static string DailyJournal_Date {
            get {
                return ResourceManager.GetString("DailyJournal_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Daily Journal Date.
        /// </summary>
        public static string DailyJournal_DateError {
            get {
                return ResourceManager.GetString("DailyJournal_DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyJournal ID.
        /// </summary>
        public static string DailyJournal_ID {
            get {
                return ResourceManager.GetString("DailyJournal_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Journal DetailID.
        /// </summary>
        public static string DailyJournalDetail_ID {
            get {
                return ResourceManager.GetString("DailyJournalDetail_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference Between Debit and Credite.
        /// </summary>
        public static string differencebetweendebitandcredite {
            get {
                return ResourceManager.GetString("differencebetweendebitandcredite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Number.
        /// </summary>
        public static string Document_Number {
            get {
                return ResourceManager.GetString("Document_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Document  Number .
        /// </summary>
        public static string Document_NumberError {
            get {
                return ResourceManager.GetString("Document_NumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  statement .
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Arabic statement .
        /// </summary>
        public static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Enter   Arabic statement.
        /// </summary>
        public static string Note1Error {
            get {
                return ResourceManager.GetString("Note1Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Enter  statement.
        /// </summary>
        public static string NoteError {
            get {
                return ResourceManager.GetString("NoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center Description.
        /// </summary>
        public static string operationDescription {
            get {
                return ResourceManager.GetString("operationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value original currency.
        /// </summary>
        public static string originalamount {
            get {
                return ResourceManager.GetString("originalamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Year.
        /// </summary>
        public static string PhysicalYear {
            get {
                return ResourceManager.GetString("PhysicalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No..
        /// </summary>
        public static string Serial_No {
            get {
                return ResourceManager.GetString("Serial_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Serial Number .
        /// </summary>
        public static string Serial_NoError {
            get {
                return ResourceManager.GetString("Serial_NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center Name.
        /// </summary>
        public static string StatementType {
            get {
                return ResourceManager.GetString("StatementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Statement Type.
        /// </summary>
        public static string StatementTypeE {
            get {
                return ResourceManager.GetString("StatementTypeE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Type .
        /// </summary>
        public static string StatementTypeName {
            get {
                return ResourceManager.GetString("StatementTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transation Rate.
        /// </summary>
        public static string TransationRate {
            get {
                return ResourceManager.GetString("TransationRate", resourceCulture);
            }
        }
    }
}
