//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DepartmentTrees {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DepartmentTrees() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.DepartmentTrees", typeof(DepartmentTrees).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub Department.
        /// </summary>
        public static string AddsubDepartment {
            get {
                return ResourceManager.GetString("AddsubDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string BankCurrencyID {
            get {
                return ResourceManager.GetString("BankCurrencyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Currency.
        /// </summary>
        public static string BankCurrencyIDError {
            get {
                return ResourceManager.GetString("BankCurrencyIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        public static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID.
        /// </summary>
        public static string DepartmentID {
            get {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Level.
        /// </summary>
        public static string DepartmentLevel {
            get {
                return ResourceManager.GetString("DepartmentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Department Level.
        /// </summary>
        public static string DepartmentLevelError {
            get {
                return ResourceManager.GetString("DepartmentLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name Ar.
        /// </summary>
        public static string DepartmentNameAr {
            get {
                return ResourceManager.GetString("DepartmentNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Department  Name.
        /// </summary>
        public static string DepartmentNameArError {
            get {
                return ResourceManager.GetString("DepartmentNameArError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Existed.
        /// </summary>
        public static string DepartmentNameArExist {
            get {
                return ResourceManager.GetString("DepartmentNameArExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name EN.
        /// </summary>
        public static string DepartmentNameEN {
            get {
                return ResourceManager.GetString("DepartmentNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Department  Name.
        /// </summary>
        public static string DepartmentNameENError {
            get {
                return ResourceManager.GetString("DepartmentNameENError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Parent.
        /// </summary>
        public static string DepartmentParent {
            get {
                return ResourceManager.GetString("DepartmentParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Department  Parent.
        /// </summary>
        public static string DepartmentParentError {
            get {
                return ResourceManager.GetString("DepartmentParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Parent Name Ar.
        /// </summary>
        public static string DepartmentParentNameAr {
            get {
                return ResourceManager.GetString("DepartmentParentNameAr", resourceCulture);
            }
        }
    }
}
