//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Employee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Employee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.Employee", typeof(Employee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Address.
        /// </summary>
        public static string Addresserror {
            get {
                return ResourceManager.GetString("Addresserror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select your Birth Date.
        /// </summary>
        public static string BirthDateerror {
            get {
                return ResourceManager.GetString("BirthDateerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Place.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Number.
        /// </summary>
        public static string childNumber {
            get {
                return ResourceManager.GetString("childNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companions Count.
        /// </summary>
        public static string companionscount {
            get {
                return ResourceManager.GetString("companionscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Duration.
        /// </summary>
        public static string ContractDuration {
            get {
                return ResourceManager.GetString("ContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DeptID {
            get {
                return ResourceManager.GetString("DeptID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational level.
        /// </summary>
        public static string Educationallevel {
            get {
                return ResourceManager.GetString("Educationallevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email.
        /// </summary>
        public static string Emailerror {
            get {
                return ResourceManager.GetString("Emailerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string Employee_ID {
            get {
                return ResourceManager.GetString("Employee_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        public static string EmployeeNumber {
            get {
                return ResourceManager.GetString("EmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الموظف .
        /// </summary>
        public static string EmployeeStatus {
            get {
                return ResourceManager.GetString("EmployeeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date of  identity issuance.
        /// </summary>
        public static string EndNational_ID_date {
            get {
                return ResourceManager.GetString("EndNational_ID_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date of Passport.
        /// </summary>
        public static string Endpassport_date {
            get {
                return ResourceManager.GetString("Endpassport_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterance Border.
        /// </summary>
        public static string EnteranceBorder {
            get {
                return ResourceManager.GetString("EnteranceBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterance Border Date.
        /// </summary>
        public static string EnteranceDate {
            get {
                return ResourceManager.GetString("EnteranceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string ImgUrl {
            get {
                return ResourceManager.GetString("ImgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job.
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job.
        /// </summary>
        public static string jobID {
            get {
                return ResourceManager.GetString("jobID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select your job.
        /// </summary>
        public static string jobIDerror {
            get {
                return ResourceManager.GetString("jobIDerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job License Number.
        /// </summary>
        public static string JoblicenseNumber {
            get {
                return ResourceManager.GetString("JoblicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital status.
        /// </summary>
        public static string Maritalstatus {
            get {
                return ResourceManager.GetString("Maritalstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Mobile.
        /// </summary>
        public static string Mobileerror {
            get {
                return ResourceManager.GetString("Mobileerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string NameA {
            get {
                return ResourceManager.GetString("NameA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Arabic Name.
        /// </summary>
        public static string NameAerror {
            get {
                return ResourceManager.GetString("NameAerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string NameE {
            get {
                return ResourceManager.GetString("NameE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter English Name.
        /// </summary>
        public static string NameEerror {
            get {
                return ResourceManager.GetString("NameEerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string National_ID {
            get {
                return ResourceManager.GetString("National_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your National ID.
        /// </summary>
        public static string National_IDerror {
            get {
                return ResourceManager.GetString("National_IDerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string NationalityID {
            get {
                return ResourceManager.GetString("NationalityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Nationality.
        /// </summary>
        public static string NationalityIDerror {
            get {
                return ResourceManager.GetString("NationalityIDerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Enter Border.
        /// </summary>
        public static string NumberEnterBorder {
            get {
                return ResourceManager.GetString("NumberEnterBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string passportNumber {
            get {
                return ResourceManager.GetString("passportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Passport.
        /// </summary>
        public static string passportpleace {
            get {
                return ResourceManager.GetString("passportpleace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Phone.
        /// </summary>
        public static string Phoneerror {
            get {
                return ResourceManager.GetString("Phoneerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of identity issuance.
        /// </summary>
        public static string pleaceNational_ID {
            get {
                return ResourceManager.GetString("pleaceNational_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Start Date of identity issuance.
        /// </summary>
        public static string ReleaseNational_ID_date {
            get {
                return ResourceManager.GetString("ReleaseNational_ID_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date of Passport .
        /// </summary>
        public static string Releasepassport_date {
            get {
                return ResourceManager.GetString("Releasepassport_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string religion {
            get {
                return ResourceManager.GetString("religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Certificate.
        /// </summary>
        public static string scientificcertificate {
            get {
                return ResourceManager.GetString("scientificcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Date.
        /// </summary>
        public static string visadate {
            get {
                return ResourceManager.GetString("visadate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobin Visa.
        /// </summary>
        public static string visajob {
            get {
                return ResourceManager.GetString("visajob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Number.
        /// </summary>
        public static string visaNumber {
            get {
                return ResourceManager.GetString("visaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string WorkDate {
            get {
                return ResourceManager.GetString("WorkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select your Hire Date.
        /// </summary>
        public static string WorkDateerror {
            get {
                return ResourceManager.GetString("WorkDateerror", resourceCulture);
            }
        }
    }
}
