//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.GeneralResource", typeof(GeneralResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academics.
        /// </summary>
        public static string AcademicConfigration {
            get {
                return ResourceManager.GetString("AcademicConfigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year.
        /// </summary>
        public static string AcademicYear {
            get {
                return ResourceManager.GetString("AcademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Grades.
        /// </summary>
        public static string AcademicYearName {
            get {
                return ResourceManager.GetString("AcademicYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Account .
        /// </summary>
        public static string AccountChild {
            get {
                return ResourceManager.GetString("AccountChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Fee Types.
        /// </summary>
        public static string AccountFeeTypes {
            get {
                return ResourceManager.GetString("AccountFeeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting .
        /// </summary>
        public static string accounting {
            get {
                return ResourceManager.GetString("accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting System.
        /// </summary>
        public static string AccountingConfigration {
            get {
                return ResourceManager.GetString("AccountingConfigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Level 2.
        /// </summary>
        public static string AccountLevel2 {
            get {
                return ResourceManager.GetString("AccountLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allow to Add Account.
        /// </summary>
        public static string AccountLevelError {
            get {
                return ResourceManager.GetString("AccountLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Prof.
        /// </summary>
        public static string AccountProf {
            get {
                return ResourceManager.GetString("AccountProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouns &amp; Deduction Item.
        /// </summary>
        public static string AccountSalaryItem {
            get {
                return ResourceManager.GetString("AccountSalaryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Chart.
        /// </summary>
        public static string AccountTree {
            get {
                return ResourceManager.GetString("AccountTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Chart .
        /// </summary>
        public static string AccounttreeName {
            get {
                return ResourceManager.GetString("AccounttreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed to Add Asset.
        /// </summary>
        public static string AssetLevelError {
            get {
                return ResourceManager.GetString("AssetLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Structure.
        /// </summary>
        public static string AssetTree {
            get {
                return ResourceManager.GetString("AssetTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bachelor&apos;s degree.
        /// </summary>
        public static string bachelorsdegree {
            get {
                return ResourceManager.GetString("bachelorsdegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        public static string balancesheet {
            get {
                return ResourceManager.GetString("balancesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Branch.
        /// </summary>
        public static string BankBranch {
            get {
                return ResourceManager.GetString("BankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Configration.
        /// </summary>
        public static string BankConfigration {
            get {
                return ResourceManager.GetString("BankConfigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank currency.
        /// </summary>
        public static string Bankcurrency {
            get {
                return ResourceManager.GetString("Bankcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks.
        /// </summary>
        public static string banks {
            get {
                return ResourceManager.GetString("banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Transactions.
        /// </summary>
        public static string BankTransactions {
            get {
                return ResourceManager.GetString("BankTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Employee Salary.
        /// </summary>
        public static string BasicEmployeeSalary {
            get {
                return ResourceManager.GetString("BasicEmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonds.
        /// </summary>
        public static string Bonds {
            get {
                return ResourceManager.GetString("Bonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouns &amp; Deduction.
        /// </summary>
        public static string BounsDeduction {
            get {
                return ResourceManager.GetString("BounsDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Account.
        /// </summary>
        public static string BranchAccount {
            get {
                return ResourceManager.GetString("BranchAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Cost.
        /// </summary>
        public static string BusCost {
            get {
                return ResourceManager.GetString("BusCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Expenses.
        /// </summary>
        public static string BusExpenses {
            get {
                return ResourceManager.GetString("BusExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Student Occupation.
        /// </summary>
        public static string BusStudentOccupation {
            get {
                return ResourceManager.GetString("BusStudentOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Trip.
        /// </summary>
        public static string BusTrip {
            get {
                return ResourceManager.GetString("BusTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Payable.
        /// </summary>
        public static string CashPayable {
            get {
                return ResourceManager.GetString("CashPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cheques Payable.
        /// </summary>
        public static string chequesPayable {
            get {
                return ResourceManager.GetString("chequesPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cheques Receivable.
        /// </summary>
        public static string chequesReceivable {
            get {
                return ResourceManager.GetString("chequesReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian.
        /// </summary>
        public static string Christian {
            get {
                return ResourceManager.GetString("Christian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Room.
        /// </summary>
        public static string ClassRoom {
            get {
                return ResourceManager.GetString("ClassRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Physical Year.
        /// </summary>
        public static string ClosePhysicalYear {
            get {
                return ResourceManager.GetString("ClosePhysicalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  password not  matched..
        /// </summary>
        public static string ComparePassworderror {
            get {
                return ResourceManager.GetString("ComparePassworderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Information.
        /// </summary>
        public static string ConfigHeader {
            get {
                return ResourceManager.GetString("ConfigHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations.
        /// </summary>
        public static string Configs {
            get {
                return ResourceManager.GetString("Configs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Confirm  Password.
        /// </summary>
        public static string ConfirmPassworderror {
            get {
                return ResourceManager.GetString("ConfirmPassworderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string CostCenter {
            get {
                return ResourceManager.GetString("CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string Createdby {
            get {
                return ResourceManager.GetString("Createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string DailyJournal {
            get {
                return ResourceManager.GetString("DailyJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit and Credit Not Equal.
        /// </summary>
        public static string DailyJournalequal {
            get {
                return ResourceManager.GetString("DailyJournalequal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted Journals.
        /// </summary>
        public static string DailyJournalPosted {
            get {
                return ResourceManager.GetString("DailyJournalPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journalposted Created.
        /// </summary>
        public static string DailyJournalpostedCreated {
            get {
                return ResourceManager.GetString("DailyJournalpostedCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Posted Journals  .
        /// </summary>
        public static string DailyJournalUNPosted {
            get {
                return ResourceManager.GetString("DailyJournalUNPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal unposted Created.
        /// </summary>
        public static string DailyJournalunpostedCreated {
            get {
                return ResourceManager.GetString("DailyJournalunpostedCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Off.
        /// </summary>
        public static string DaysOff {
            get {
                return ResourceManager.GetString("DaysOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You  Want To Delete.
        /// </summary>
        public static string DeleteMessageConfirm {
            get {
                return ResourceManager.GetString("DeleteMessageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allow to Add Department.
        /// </summary>
        public static string DepartmentLevelError {
            get {
                return ResourceManager.GetString("DepartmentLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Structure.
        /// </summary>
        public static string DepartmentTree {
            get {
                return ResourceManager.GetString("DepartmentTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation.
        /// </summary>
        public static string depreciation {
            get {
                return ResourceManager.GetString("depreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or Remove {0} from the Grid below.
        /// </summary>
        public static string DescriptionAddRemove {
            get {
                return ResourceManager.GetString("DescriptionAddRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to divorced.
        /// </summary>
        public static string divorced {
            get {
                return ResourceManager.GetString("divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctorate.
        /// </summary>
        public static string Doctorate {
            get {
                return ResourceManager.GetString("Doctorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download PDF.
        /// </summary>
        public static string DownloadPdf {
            get {
                return ResourceManager.GetString("DownloadPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Invaild E-Mail Format .
        /// </summary>
        public static string E_mailerror {
            get {
                return ResourceManager.GetString("E_mailerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees .
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Salary Report.
        /// </summary>
        public static string EmployeeSalaryReport {
            get {
                return ResourceManager.GetString("EmployeeSalaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Salaries.
        /// </summary>
        public static string EmployeesMonthlySalaries {
            get {
                return ResourceManager.GetString("EmployeesMonthlySalaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance.
        /// </summary>
        public static string FirstBalance {
            get {
                return ResourceManager.GetString("FirstBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth Branch.
        /// </summary>
        public static string FourthBranch {
            get {
                return ResourceManager.GetString("FourthBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frist Branche.
        /// </summary>
        public static string FristBranche {
            get {
                return ResourceManager.GetString("FristBranche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general Accounting.
        /// </summary>
        public static string generalaccounting {
            get {
                return ResourceManager.GetString("generalaccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        public static string Generalbudget {
            get {
                return ResourceManager.GetString("Generalbudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string Generaldefinitions {
            get {
                return ResourceManager.GetString("Generaldefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Students.
        /// </summary>
        public static string GetStudents {
            get {
                return ResourceManager.GetString("GetStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High School.
        /// </summary>
        public static string HighSchool {
            get {
                return ResourceManager.GetString("HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HolidayTypes.
        /// </summary>
        public static string HolidayTypes {
            get {
                return ResourceManager.GetString("HolidayTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources.
        /// </summary>
        public static string hr {
            get {
                return ResourceManager.GetString("hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Select Image.
        /// </summary>
        public static string ImageRequire {
            get {
                return ResourceManager.GetString("ImageRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate.
        /// </summary>
        public static string Immediate {
            get {
                return ResourceManager.GetString("Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statement.
        /// </summary>
        public static string IncomeStatement {
            get {
                return ResourceManager.GetString("IncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Registration.
        /// </summary>
        public static string InitialRegistration {
            get {
                return ResourceManager.GetString("InitialRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment.
        /// </summary>
        public static string Installment {
            get {
                return ResourceManager.GetString("Installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed to Add Inventory Item.
        /// </summary>
        public static string InventoryLevelError {
            get {
                return ResourceManager.GetString("InventoryLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Structure.
        /// </summary>
        public static string InventoryTree {
            get {
                return ResourceManager.GetString("InventoryTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Types.
        /// </summary>
        public static string JournalTypes {
            get {
                return ResourceManager.GetString("JournalTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger.
        /// </summary>
        public static string Ledger {
            get {
                return ResourceManager.GetString("Ledger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string logoff {
            get {
                return ResourceManager.GetString("logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Account.
        /// </summary>
        public static string MainAccount {
            get {
                return ResourceManager.GetString("MainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Branch.
        /// </summary>
        public static string MainBranch {
            get {
                return ResourceManager.GetString("MainBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master&apos;s degree.
        /// </summary>
        public static string mastersdegree {
            get {
                return ResourceManager.GetString("mastersdegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Manufacture.
        /// </summary>
        public static string MaterialManufacture {
            get {
                return ResourceManager.GetString("MaterialManufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiedby.
        /// </summary>
        public static string Modifiedby {
            get {
                return ResourceManager.GetString("Modifiedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muslim.
        /// </summary>
        public static string Muslim {
            get {
                return ResourceManager.GetString("Muslim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Arabic is Required.
        /// </summary>
        public static string NameArError {
            get {
                return ResourceManager.GetString("NameArError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is Required .
        /// </summary>
        public static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this record, record used in other processes .
        /// </summary>
        public static string NotAllowedDelete {
            get {
                return ResourceManager.GetString("NotAllowedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes payable.
        /// </summary>
        public static string Notespayable {
            get {
                return ResourceManager.GetString("Notespayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Receivable.
        /// </summary>
        public static string NotesReceivable {
            get {
                return ResourceManager.GetString("NotesReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        public static string Passworderror {
            get {
                return ResourceManager.GetString("Passworderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petty cash.
        /// </summary>
        public static string Pettycash {
            get {
                return ResourceManager.GetString("Pettycash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year.
        /// </summary>
        public static string PhysicalYear {
            get {
                return ResourceManager.GetString("PhysicalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST.
        /// </summary>
        public static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        public static string Posted {
            get {
                return ResourceManager.GetString("Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation.
        /// </summary>
        public static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qurter.
        /// </summary>
        public static string Qurter {
            get {
                return ResourceManager.GetString("Qurter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Items.
        /// </summary>
        public static string ReceiveItems {
            get {
                return ResourceManager.GetString("ReceiveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cash Recivable .
        /// </summary>
        public static string ReciveCash {
            get {
                return ResourceManager.GetString("ReciveCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Be Number.
        /// </summary>
        public static string Reg_ExpDigit {
            get {
                return ResourceManager.GetString("Reg_ExpDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Be Numbers.
        /// </summary>
        public static string Reg_Expmoney {
            get {
                return ResourceManager.GetString("Reg_Expmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        public static string reviews {
            get {
                return ResourceManager.GetString("reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name is Required.
        /// </summary>
        public static string RolesNameError {
            get {
                return ResourceManager.GetString("RolesNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books price and StudyFees .
        /// </summary>
        public static string SchoolFeesList {
            get {
                return ResourceManager.GetString("SchoolFeesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string SchoolUser {
            get {
                return ResourceManager.GetString("SchoolUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Branche.
        /// </summary>
        public static string SecondBranche {
            get {
                return ResourceManager.GetString("SecondBranche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single.
        /// </summary>
        public static string single {
            get {
                return ResourceManager.GetString("single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Type.
        /// </summary>
        public static string StatementType {
            get {
                return ResourceManager.GetString("StatementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Places.
        /// </summary>
        public static string StorePlaces {
            get {
                return ResourceManager.GetString("StorePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Configration.
        /// </summary>
        public static string Student_Configration {
            get {
                return ResourceManager.GetString("Student_Configration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student  Fees.
        /// </summary>
        public static string Student_fees {
            get {
                return ResourceManager.GetString("Student_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Fees.
        /// </summary>
        public static string StudentFees {
            get {
                return ResourceManager.GetString("StudentFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student fees History.
        /// </summary>
        public static string StudentfeesHistory {
            get {
                return ResourceManager.GetString("StudentfeesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudyYear.
        /// </summary>
        public static string StudyYear {
            get {
                return ResourceManager.GetString("StudyYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsidiary ledger.
        /// </summary>
        public static string subsidiaryledger {
            get {
                return ResourceManager.GetString("subsidiaryledger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Branche.
        /// </summary>
        public static string ThirdBranche {
            get {
                return ResourceManager.GetString("ThirdBranche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete is a SuccessFully Done.
        /// </summary>
        public static string toastrDelete {
            get {
                return ResourceManager.GetString("toastrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit is a SuccessFully Done.
        /// </summary>
        public static string toastrEdit {
            get {
                return ResourceManager.GetString("toastrEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is Exist.
        /// </summary>
        public static string toastrEmailExist {
            get {
                return ResourceManager.GetString("toastrEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Operation id Faild.
        /// </summary>
        public static string toastrOperationFaild {
            get {
                return ResourceManager.GetString("toastrOperationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save is a SuccessFully Done.
        /// </summary>
        public static string toastrSave {
            get {
                return ResourceManager.GetString("toastrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fees.
        /// </summary>
        public static string TotalFees {
            get {
                return ResourceManager.GetString("TotalFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string Transportation {
            get {
                return ResourceManager.GetString("Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasury Stock.
        /// </summary>
        public static string Treasury {
            get {
                return ResourceManager.GetString("Treasury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Balance.
        /// </summary>
        public static string TrialBalance {
            get {
                return ResourceManager.GetString("TrialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Measurements.
        /// </summary>
        public static string UnitsMeasurements {
            get {
                return ResourceManager.GetString("UnitsMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNPOST.
        /// </summary>
        public static string unpost {
            get {
                return ResourceManager.GetString("unpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User to Roles .
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus ERP .
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widower.
        /// </summary>
        public static string Widower {
            get {
                return ResourceManager.GetString("Widower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With salary.
        /// </summary>
        public static string Withsalary {
            get {
                return ResourceManager.GetString("Withsalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yearly.
        /// </summary>
        public static string yearly {
            get {
                return ResourceManager.GetString("yearly", resourceCulture);
            }
        }
    }
}
