//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InventoryTree {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InventoryTree() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.InventoryTree", typeof(InventoryTree).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub Inventory.
        /// </summary>
        public static string AddsubInventory {
            get {
                return ResourceManager.GetString("AddsubInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Code.
        /// </summary>
        public static string InventoryCode {
            get {
                return ResourceManager.GetString("InventoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory ID.
        /// </summary>
        public static string InventoryID {
            get {
                return ResourceManager.GetString("InventoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Level.
        /// </summary>
        public static string InventoryLevel {
            get {
                return ResourceManager.GetString("InventoryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Inventory Level.
        /// </summary>
        public static string InventoryLevelError {
            get {
                return ResourceManager.GetString("InventoryLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Name Ar.
        /// </summary>
        public static string InventoryNameAr {
            get {
                return ResourceManager.GetString("InventoryNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Inventory  Name.
        /// </summary>
        public static string InventoryNameArError {
            get {
                return ResourceManager.GetString("InventoryNameArError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Existed.
        /// </summary>
        public static string InventoryNameArExist {
            get {
                return ResourceManager.GetString("InventoryNameArExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Name EN.
        /// </summary>
        public static string InventoryNameEN {
            get {
                return ResourceManager.GetString("InventoryNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Inventory  Name.
        /// </summary>
        public static string InventoryNameENError {
            get {
                return ResourceManager.GetString("InventoryNameENError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Parent.
        /// </summary>
        public static string InventoryParent {
            get {
                return ResourceManager.GetString("InventoryParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter  Inventory  Parent.
        /// </summary>
        public static string InventoryParentError {
            get {
                return ResourceManager.GetString("InventoryParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Parent Name Ar.
        /// </summary>
        public static string InventoryParentNameAr {
            get {
                return ResourceManager.GetString("InventoryParentNameAr", resourceCulture);
            }
        }
    }
}
