//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Transport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.School.Management.Logic.Resources.Transport", typeof(Transport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Seats .
        /// </summary>
        public static string AvailableSeats {
            get {
                return ResourceManager.GetString("AvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Name (Arabic).
        /// </summary>
        public static string BusNameAr {
            get {
                return ResourceManager.GetString("BusNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Name .
        /// </summary>
        public static string BusNameEn {
            get {
                return ResourceManager.GetString("BusNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Number.
        /// </summary>
        public static string BusNumber {
            get {
                return ResourceManager.GetString("BusNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver .
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name (Arabic).
        /// </summary>
        public static string DriverNameAr {
            get {
                return ResourceManager.GetString("DriverNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        public static string DriverNameEn {
            get {
                return ResourceManager.GetString("DriverNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id.
        /// </summary>
        public static string EmployeeId {
            get {
                return ResourceManager.GetString("EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Point.
        /// </summary>
        public static string FarestPoint {
            get {
                return ResourceManager.GetString("FarestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Point Cost .
        /// </summary>
        public static string FarestPointCost {
            get {
                return ResourceManager.GetString("FarestPointCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Point Discount .
        /// </summary>
        public static string FarestPointDiscount {
            get {
                return ResourceManager.GetString("FarestPointDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expiry Date .
        /// </summary>
        public static string LicenseExpiryDate {
            get {
                return ResourceManager.GetString("LicenseExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number .
        /// </summary>
        public static string LicenseNumber {
            get {
                return ResourceManager.GetString("LicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer&apos;s Name.
        /// </summary>
        public static string ManufacturerName {
            get {
                return ResourceManager.GetString("ManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model .
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number .
        /// </summary>
        public static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Name (Arabic).
        /// </summary>
        public static string SupervisorNameAr {
            get {
                return ResourceManager.GetString("SupervisorNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Name .
        /// </summary>
        public static string SupervisorNameEn {
            get {
                return ResourceManager.GetString("SupervisorNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Seats .
        /// </summary>
        public static string TotalSeats {
            get {
                return ResourceManager.GetString("TotalSeats", resourceCulture);
            }
        }
    }
}
