//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDailyJournalDetail
    {
        public int DailyJournalDetailID { get; set; }
        public int DailyJournalID { get; set; }
        public int AccountTreeID { get; set; }
        public string Description { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CostCenterID { get; set; }
        public Nullable<int> SchoolID { get; set; }
    
        public virtual AccountCostCenter AccountCostCenter { get; set; }
        public virtual AccountDailyJournal AccountDailyJournal { get; set; }
        public virtual AccountTree AccountTree { get; set; }
    }
}
