//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accountchequesreceivable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accountchequesreceivable()
        {
            this.AccStudentFees = new HashSet<AccStudentFee>();
        }
    
        public int ID { get; set; }
        public string InvoiceCode { get; set; }
        public string docementNumber { get; set; }
        public Nullable<int> costcenter { get; set; }
        public Nullable<int> BankBranchID { get; set; }
        public Nullable<int> fromAccount { get; set; }
        public Nullable<int> AccountTreeID { get; set; }
        public Nullable<System.DateTime> operationDate { get; set; }
        public Nullable<System.DateTime> collectionDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> isCollected { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> BankCurrencyID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<int> DailyJournalID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> PhysicalYearID { get; set; }
    
        public virtual AccountCostCenter AccountCostCenter { get; set; }
        public virtual AccountDailyJournal AccountDailyJournal { get; set; }
        public virtual AdmCompany AdmCompany { get; set; }
        public virtual AdmEmployee AdmEmployee { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
        public virtual BankBranch BankBranch { get; set; }
        public virtual BankCurrency BankCurrency { get; set; }
        public virtual PhysicalYear PhysicalYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccStudentFee> AccStudentFees { get; set; }
        public virtual AccountTree AccountTree { get; set; }
        public virtual AccountTree AccountTree1 { get; set; }
        public virtual Bank Bank { get; set; }
    }
}
