//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDailyJournal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountDailyJournal()
        {
            this.AccountchequePayables = new HashSet<AccountchequePayable>();
            this.Accountchequesreceivables = new HashSet<Accountchequesreceivable>();
            this.AccountDailyJournalDetails = new HashSet<AccountDailyJournalDetail>();
            this.AccountPayableCashes = new HashSet<AccountPayableCash>();
            this.AccountReciveCashes = new HashSet<AccountReciveCash>();
            this.AccStudentFees = new HashSet<AccStudentFee>();
            this.HRPayrollEmployeeBenfitsOthers = new HashSet<HRPayrollEmployeeBenfitsOther>();
        }
    
        public int DailyJournalID { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public string Note { get; set; }
        public string DocumentNumber { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> BankCurrencyID { get; set; }
        public Nullable<decimal> TransationRate { get; set; }
        public string Description { get; set; }
        public int PhysicalYearID { get; set; }
        public Nullable<System.DateTime> DailyJournalDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApprove { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public bool IsPost { get; set; }
        public Nullable<int> PostedbyID { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string Note1 { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> JournalType { get; set; }
        public string AttachedDocName { get; set; }
    
        public virtual BankCurrency BankCurrency { get; set; }
        public virtual PhysicalYear PhysicalYear { get; set; }
        public virtual AdmCompany AdmCompany { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
        public virtual JournalType JournalType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountchequePayable> AccountchequePayables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accountchequesreceivable> Accountchequesreceivables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountDailyJournalDetail> AccountDailyJournalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPayableCash> AccountPayableCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountReciveCash> AccountReciveCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccStudentFee> AccStudentFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPayrollEmployeeBenfitsOther> HRPayrollEmployeeBenfitsOthers { get; set; }
    }
}
