//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEmployeesMonthlySalary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountEmployeesMonthlySalary()
        {
            this.EmployeeVacations = new HashSet<EmployeeVacation>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> AdditionalSalary { get; set; }
        public Nullable<decimal> AllowanceSalary { get; set; }
        public Nullable<decimal> BonusesSalary { get; set; }
        public Nullable<decimal> extraSalary { get; set; }
        public Nullable<decimal> TotalSalary { get; set; }
        public Nullable<decimal> Socialinsurance { get; set; }
        public Nullable<decimal> Medicalinsurance { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> Dedecation { get; set; }
        public Nullable<decimal> TotalDedecated { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<decimal> AllowanceSalary2 { get; set; }
        public Nullable<decimal> AllowanceSalary3 { get; set; }
        public Nullable<int> workingHours { get; set; }
        public Nullable<int> BankBranchID { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Transitionallowance { get; set; }
        public Nullable<decimal> Subsistenceallowance { get; set; }
        public Nullable<decimal> Drivingallowance { get; set; }
        public Nullable<decimal> conditionsworkallowance { get; set; }
        public string Airline { get; set; }
        public string Airlineclass { get; set; }
        public string accommodationallowancetype { get; set; }
        public Nullable<decimal> accommodationallowanc { get; set; }
        public Nullable<System.DateTime> valuedate { get; set; }
        public Nullable<int> leavebalance { get; set; }
        public Nullable<int> LBperMonth { get; set; }
        public Nullable<int> flighttickets { get; set; }
        public Nullable<int> FTperMonth { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public string paymentsalariesway { get; set; }
        public Nullable<int> DailyJournalID { get; set; }
        public Nullable<int> CashPayableID { get; set; }
        public Nullable<int> ChequePayableID { get; set; }
        public System.DateTime SalaryOfMonth { get; set; }
    
        public virtual AdmEmployee AdmEmployee { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
        public virtual AdmDepartment AdmDepartment { get; set; }
        public virtual BankBranch BankBranch { get; set; }
        public virtual AccountEmployeesMonthlySalary AccountEmployeesMonthlySalary1 { get; set; }
        public virtual AccountEmployeesMonthlySalary AccountEmployeesMonthlySalary2 { get; set; }
        public virtual AccountEmployeesMonthlySalary AccountEmployeesMonthlySalary11 { get; set; }
        public virtual AccountEmployeesMonthlySalary AccountEmployeesMonthlySalary3 { get; set; }
        public virtual AccountEmployeesMonthlySalary AccountEmployeesMonthlySalary12 { get; set; }
        public virtual AccountEmployeesMonthlySalary AccountEmployeesMonthlySalary4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeVacation> EmployeeVacations { get; set; }
        public virtual AccountchequePayable AccountchequePayable { get; set; }
        public virtual AdmJob AdmJob { get; set; }
    }
}
