//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEmployeeSalaryItem
    {
        public int ID { get; set; }
        public int Employee_ID { get; set; }
        public int SalaryItemTypeID { get; set; }
        public int SalaryItemID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public string BounsType { get; set; }
        public int CompanyID { get; set; }
        public int SchoolID { get; set; }
    
        public virtual AccountSalaryItem AccountSalaryItem { get; set; }
        public virtual AdmEmployee AdmEmployee { get; set; }
        public virtual AdmCompany AdmCompany { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
    }
}
