//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountCustomer()
        {
            this.AccountCustomerTransactions = new HashSet<AccountCustomerTransaction>();
        }
    
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNameAr { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<int> AccountTreeID { get; set; }
        public Nullable<decimal> Depeit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> FBalance { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public string CustomerNumber { get; set; }
        public string Fax { get; set; }
        public string PostCode { get; set; }
        public string Typeofactivity { get; set; }
        public string Commercialregister { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> BankBranchID { get; set; }
        public string BankAccountNumber { get; set; }
        public string IBAN1 { get; set; }
        public string IBAN2 { get; set; }
        public string IBAN3 { get; set; }
        public string Customeractivity { get; set; }
        public string ReasonStop { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public string Customer_Employee { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> SchoolID { get; set; }
    
        public virtual AdmCity AdmCity { get; set; }
        public virtual AdmCompany AdmCompany { get; set; }
        public virtual AdmEmployee AdmEmployee { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
        public virtual BankBranch BankBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountCustomerTransaction> AccountCustomerTransactions { get; set; }
        public virtual AccountTree AccountTree { get; set; }
        public virtual Bank Bank { get; set; }
    }
}
