//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccStudentFee
    {
        public int ID { get; set; }
        public Nullable<long> StudRefID { get; set; }
        public Nullable<int> StudentConfigrationID { get; set; }
        public Nullable<byte> PaymentType { get; set; }
        public Nullable<byte> PaymentWay { get; set; }
        public Nullable<decimal> originalAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string bankStatement { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DailyJournalID { get; set; }
        public Nullable<int> CashRecivedID { get; set; }
        public Nullable<int> ChequeRecivedID { get; set; }
        public int AccountTreeID { get; set; }
        public Nullable<int> installment { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<int> StudentDiscount { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<long> ReceiptID { get; set; }
        public string InstallmentCode { get; set; }
    
        public virtual Accountchequesreceivable Accountchequesreceivable { get; set; }
        public virtual AccountDailyJournal AccountDailyJournal { get; set; }
        public virtual AccountReciveCash AccountReciveCash { get; set; }
        public virtual AccStudentConfig AccStudentConfig { get; set; }
        public virtual StudentReference StudentReference { get; set; }
        public virtual FeeInstallmentType FeeInstallmentType { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
        public virtual SchoolUser SchoolUser { get; set; }
        public virtual SchoolUser SchoolUser1 { get; set; }
        public virtual SchoolUser SchoolUser2 { get; set; }
        public virtual AccountTree AccountTree { get; set; }
    }
}
