//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccStudentConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccStudentConfig()
        {
            this.AccStudentFees = new HashSet<AccStudentFee>();
        }
    
        public int ID { get; set; }
        public double Discount { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public long Ref_Id { get; set; }
        public int AccountTreeID { get; set; }
        public int SchoolID { get; set; }
    
        public virtual StudentReference StudentReference { get; set; }
        public virtual AccStudentConfig AccStudentConfig1 { get; set; }
        public virtual AccStudentConfig AccStudentConfig2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccStudentFee> AccStudentFees { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
        public virtual AccountTree AccountTree { get; set; }
    }
}
