//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdmEmployee()
        {
            this.AccountEmployeeSalaryItems = new HashSet<AccountEmployeeSalaryItem>();
            this.AccountEmployeesMonthlySalaries = new HashSet<AccountEmployeesMonthlySalary>();
            this.AccountEmployeesSalaries = new HashSet<AccountEmployeesSalary>();
            this.BusDetails = new HashSet<BusDetail>();
            this.BusExpenses = new HashSet<BusExpens>();
            this.AdmClassRooms = new HashSet<AdmClassRoom>();
            this.EmployeeReturnHistories = new HashSet<EmployeeReturnHistory>();
            this.EmployeeVacations = new HashSet<EmployeeVacation>();
            this.EmployeeAssets = new HashSet<EmployeeAsset>();
            this.EmployeeLoans = new HashSet<EmployeeLoan>();
            this.EmployeeTerminations = new HashSet<EmployeeTermination>();
            this.InvenotryStoreKeepers = new HashSet<InvenotryStoreKeeper>();
            this.AccountchequePayables = new HashSet<AccountchequePayable>();
            this.Accountchequesreceivables = new HashSet<Accountchequesreceivable>();
            this.AccountCustomers = new HashSet<AccountCustomer>();
            this.AccountPayableCashes = new HashSet<AccountPayableCash>();
            this.AccountReciveCashes = new HashSet<AccountReciveCash>();
            this.AccountSuppliers = new HashSet<AccountSupplier>();
            this.AccountTreasuries = new HashSet<AccountTreasury>();
            this.EmployeeAddedBenefitsOthers = new HashSet<EmployeeAddedBenefitsOther>();
            this.HRPayrollEmployees = new HashSet<HRPayrollEmployee>();
        }
    
        public int Employee_ID { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string National_ID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int NationalityID { get; set; }
        public int JobID { get; set; }
        public string NameE { get; set; }
        public string NameA { get; set; }
        public string Tel { get; set; }
        public string Mail { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public string ImgUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public string pleaceNational_ID { get; set; }
        public Nullable<System.DateTime> ReleaseNational_ID_date { get; set; }
        public Nullable<System.DateTime> EndNational_ID_date { get; set; }
        public string EmployeeNumber { get; set; }
        public string BirthPlace { get; set; }
        public string Maritalstatus { get; set; }
        public Nullable<int> childNumber { get; set; }
        public Nullable<int> companionscount { get; set; }
        public string sex { get; set; }
        public string religion { get; set; }
        public string passportNumber { get; set; }
        public Nullable<System.DateTime> Releasepassport_date { get; set; }
        public Nullable<System.DateTime> Endpassport_date { get; set; }
        public string passportpleace { get; set; }
        public string visaNumber { get; set; }
        public Nullable<System.DateTime> visadate { get; set; }
        public string visajob { get; set; }
        public string NumberEnterBorder { get; set; }
        public string EnteranceBorder { get; set; }
        public Nullable<System.DateTime> EnteranceDate { get; set; }
        public Nullable<System.DateTime> ContractDuration { get; set; }
        public string JoblicenseNumber { get; set; }
        public string Educationallevel { get; set; }
        public string scientificcertificate { get; set; }
        public string Notes { get; set; }
        public bool EmployeeStatus { get; set; }
        public int CompanyID { get; set; }
        public int SchoolID { get; set; }
        public string SponsorName { get; set; }
        public bool IsTerminated { get; set; }
        public int BasePay { get; set; }
        public int WorkHrs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountEmployeeSalaryItem> AccountEmployeeSalaryItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountEmployeesMonthlySalary> AccountEmployeesMonthlySalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountEmployeesSalary> AccountEmployeesSalaries { get; set; }
        public virtual Nationality Nationality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusDetail> BusDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusExpens> BusExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmClassRoom> AdmClassRooms { get; set; }
        public virtual AdmDepartment AdmDepartment { get; set; }
        public virtual AdmCompany AdmCompany { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeReturnHistory> EmployeeReturnHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeVacation> EmployeeVacations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAsset> EmployeeAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLoan> EmployeeLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTermination> EmployeeTerminations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvenotryStoreKeeper> InvenotryStoreKeepers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountchequePayable> AccountchequePayables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accountchequesreceivable> Accountchequesreceivables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountCustomer> AccountCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPayableCash> AccountPayableCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountReciveCash> AccountReciveCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountSupplier> AccountSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTreasury> AccountTreasuries { get; set; }
        public virtual DepartmentTree DepartmentTree { get; set; }
        public virtual AdmJob AdmJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAddedBenefitsOther> EmployeeAddedBenefitsOthers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPayrollEmployee> HRPayrollEmployees { get; set; }
    }
}
