//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class admGrade
    {
        public int GradeID { get; set; }
        public string GNameE { get; set; }
        public string GNameA { get; set; }
        public Nullable<bool> Is_Upload { get; set; }
        public Nullable<bool> Is_Update { get; set; }
    }
}
