//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmGradesSchool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdmGradesSchool()
        {
            this.StudentReferences = new HashSet<StudentReference>();
            this.AdmInitialStudRegistrations = new HashSet<AdmInitialStudRegistration>();
        }
    
        public string YearID { get; set; }
        public int GradeID { get; set; }
        public int GradeOrig { get; set; }
        public string GradeSchoolNameE { get; set; }
        public string GradeSchoolNameA { get; set; }
        public Nullable<bool> Is_Upload { get; set; }
        public Nullable<bool> Is_Update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentReference> StudentReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmInitialStudRegistration> AdmInitialStudRegistrations { get; set; }
    }
}
