//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class admStudyear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admStudyear()
        {
            this.StudentReferences = new HashSet<StudentReference>();
        }
    
        public int S1 { get; set; }
        public string YearID { get; set; }
        public string YearNameE { get; set; }
        public string YearNameA { get; set; }
        public Nullable<System.DateTime> YearStDate { get; set; }
        public Nullable<System.DateTime> YearEdDate { get; set; }
        public Nullable<int> CurrentYear { get; set; }
        public Nullable<int> CurrentSem { get; set; }
        public Nullable<int> CurrentQ { get; set; }
        public Nullable<int> CurrentWeek { get; set; }
        public Nullable<bool> Is_Upload { get; set; }
        public Nullable<bool> Is_Update { get; set; }
    
        public virtual admStudyear admStudyear1 { get; set; }
        public virtual admStudyear admStudyear2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentReference> StudentReferences { get; set; }
    }
}
