//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Action
    {
        public int ActionID { get; set; }
        public int BankID { get; set; }
        public int BranchID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string ReceiptNO { get; set; }
        public string Notes { get; set; }
        public int ActionType { get; set; }
        public string AccountNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
