//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.AccBusCosts = new HashSet<AccBusCost>();
            this.BusDetails = new HashSet<BusDetail>();
            this.BusExpenses = new HashSet<BusExpens>();
            this.BusTrips = new HashSet<BusTrip>();
        }
    
        public int BusID { get; set; }
        public string BusNo { get; set; }
        public string BusType { get; set; }
        public string Manufactur { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public string ChassisNo { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<System.DateTime> LicenseStart { get; set; }
        public Nullable<System.DateTime> LicenseEnd { get; set; }
        public string IssuedFrom { get; set; }
        public Nullable<int> PassengersNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> YearID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccBusCost> AccBusCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusDetail> BusDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusExpens> BusExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusTrip> BusTrips { get; set; }
        public virtual AdmCompany AdmCompany { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
    }
}
