//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusDetail
    {
        public int BusDetailsID { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDate { get; set; }
        public int BusID { get; set; }
        public bool IsSuperVisor { get; set; }
        public int Employee_ID { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual AdmEmployee AdmEmployee { get; set; }
    }
}
