//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAddedBenefitsOther
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeAddedBenefitsOther()
        {
            this.HRPayrollEmployeeBenfitsOthers = new HashSet<HRPayrollEmployeeBenfitsOther>();
        }
    
        public long Id { get; set; }
        public int EmployeeId { get; set; }
        public int EmployeeBenefitsOtherId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AdmEmployee AdmEmployee { get; set; }
        public virtual EmployeeBenfitsOther EmployeeBenfitsOther { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPayrollEmployeeBenfitsOther> HRPayrollEmployeeBenfitsOthers { get; set; }
    }
}
