//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPayroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRPayroll()
        {
            this.HRPayrollEmployees = new HashSet<HRPayrollEmployee>();
        }
    
        public long Id { get; set; }
        public int SalaryMonthId { get; set; }
        public Nullable<int> DepartmentTreeID { get; set; }
        public int CompanyID { get; set; }
        public int SchoolID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string PayrollYear { get; set; }
    
        public virtual AdmCompany AdmCompany { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
        public virtual DepartmentTree DepartmentTree { get; set; }
        public virtual HRSalaryMonth HRSalaryMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPayrollEmployee> HRPayrollEmployees { get; set; }
    }
}
