//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPayrollEmployeeBenfitsOther
    {
        public long Id { get; set; }
        public long PayrollEmployeesId { get; set; }
        public long AddedBenefitsOthersId { get; set; }
        public decimal Percentage { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> DailyJournalID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public int CompanyID { get; set; }
        public int SchoolID { get; set; }
    
        public virtual AccountDailyJournal AccountDailyJournal { get; set; }
        public virtual AdmCompany AdmCompany { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
        public virtual EmployeeAddedBenefitsOther EmployeeAddedBenefitsOther { get; set; }
        public virtual HRPayrollEmployee HRPayrollEmployee { get; set; }
    }
}
