//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryTree()
        {
            this.InvenotryStoreKeepers = new HashSet<InvenotryStoreKeeper>();
            this.Stores = new HashSet<Store>();
            this.InventoryTree1 = new HashSet<InventoryTree>();
            this.items = new HashSet<item>();
        }
    
        public int InventoryTreeID { get; set; }
        public string InventoryNameAR { get; set; }
        public string InventoryNameEN { get; set; }
        public string InventoryTreeCode { get; set; }
        public Nullable<int> InventoryTreeParentID { get; set; }
        public int InventoryTreeLevel { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public int SchoolID { get; set; }
        public string Notes { get; set; }
        public bool UseForStatic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvenotryStoreKeeper> InvenotryStoreKeepers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTree> InventoryTree1 { get; set; }
        public virtual InventoryTree InventoryTree2 { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> items { get; set; }
    }
}
