//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public long ItemId { get; set; }
        public string ItemNameEn { get; set; }
        public string ItemNameAr { get; set; }
        public int ItemInventoryStructureId { get; set; }
        public int ItemNumber { get; set; }
        public Nullable<int> Supplier { get; set; }
        public string PlaceofManufacture { get; set; }
        public Nullable<int> Material { get; set; }
        public string Model { get; set; }
        public decimal TotalCost { get; set; }
        public decimal purchasingCost { get; set; }
        public decimal lastPurchasingCost { get; set; }
        public string unitNumber { get; set; }
        public string barcode { get; set; }
        public decimal exchangeRate { get; set; }
        public decimal unitPrice { get; set; }
        public decimal wholesalePrice { get; set; }
        public string StoreNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedbyID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedbyID { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public Nullable<int> DeletedbyID { get; set; }
        public bool IsDeleted { get; set; }
        public int SchoolID { get; set; }
        public int CompanyID { get; set; }
    
        public virtual AccountSupplier AccountSupplier { get; set; }
        public virtual InventoryTree InventoryTree { get; set; }
        public virtual MaterialManufacture MaterialManufacture { get; set; }
    }
}
