//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.School.Management.Logic.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentReference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentReference()
        {
            this.AdmStudents = new HashSet<AdmStudent>();
            this.AccStudentConfigs = new HashSet<AccStudentConfig>();
            this.AccStudentFees = new HashSet<AccStudentFee>();
        }
    
        public long Ref_Id { get; set; }
        public string YearID { get; set; }
        public int GradeID { get; set; }
        public long StudAcdID { get; set; }
        public bool IsCurrent { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SchoolID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmStudent> AdmStudents { get; set; }
        public virtual admStudyear admStudyear { get; set; }
        public virtual AdmStudent AdmStudent { get; set; }
        public virtual AdmGradesSchool AdmGradesSchool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccStudentConfig> AccStudentConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccStudentFee> AccStudentFees { get; set; }
        public virtual AdmSchool AdmSchool { get; set; }
    }
}
